
package pv.hasnat.form;

import pv.hasnat.csv.ColumnNotConfiguredException;
import pv.hasnat.panel.CSVPanel;
import pv.hasnat.panel.TNSPanel;
import pv.hasnat.panel.WelcomePanel;
import pv.hasnat.sql.CSBIDGen;
import pv.hasnat.sql.ExistingPIDMQuery;
import pv.hasnat.sql.PIDMGen;
import pv.hasnat.sql.SJUIDGen;

import java.awt.Color;
import java.sql.SQLException;

import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Vector;


public class Main extends javax.swing.JFrame {

    /** Creates new form Main */
    public Main() {

        /* These two colors will be used by program clickables */
        black = new Color( 0, 0, 0 );
        blue = new Color( 0, 102, 255 );
        red = new Color( 255, 0 , 0 );

        initComponents();
        addWelcomeTab();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        menuBar = new javax.swing.JMenuBar();
        mainMenu = new javax.swing.JMenu();

        xlsMenuItem = new javax.swing.JMenuItem();

        csvMenuItem = new javax.swing.JMenuItem();
        connMenuItem = new javax.swing.JMenuItem();
        tnsMenuItem = new javax.swing.JMenuItem();
        menuSeparator = new javax.swing.JSeparator();
        quitMenuItem = new javax.swing.JMenuItem();
        tnsMenu = new javax.swing.JMenu();
        uploadMenuItem = new javax.swing.JMenuItem();
        appendMenuItem = new javax.swing.JMenuItem();

        xlsMenu = new javax.swing.JMenu();
        xlsUploadMenuItem = new javax.swing.JMenuItem();

        
        csvMenu = new javax.swing.JMenu();
        csvUploadMenuItem = new javax.swing.JMenuItem();
        cfgUploadMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("xlsQA -hasnat@pv.com- ");

        mainMenu.setText("Main Menu");

        /**
		xlsMenuItem.setText("Import XLS File into Database");
        xlsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xlsMenuItemActionPerformed(evt);
            }
        });
        mainMenu.add(xlsMenuItem);
*/
        csvMenuItem.setText("XLS Import");
        csvMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xlsMenuItemActionPerformed(evt);
            }
        });
        mainMenu.add(csvMenuItem);
        
        
        connMenuItem.setText("DB Login");
        connMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connMenuItemActionPerformed(evt);
            }
        });
        mainMenu.add(connMenuItem);

        tnsMenuItem.setText("DB Settings");
        tnsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnsMenuItemActionPerformed(evt);
            }
        });
        mainMenu.add(tnsMenuItem);
        mainMenu.add(menuSeparator);

        quitMenuItem.setText("Quit");
        quitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitMenuItemActionPerformed(evt);
            }
        });
        mainMenu.add(quitMenuItem);

        menuBar.add(mainMenu);

        tnsMenu.setText("TNS Maintenance");
        tnsMenu.setEnabled(false);

        uploadMenuItem.setText("Upload tnsnames.ora");
        uploadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadMenuItemActionPerformed(evt);
            }
        });
        tnsMenu.add(uploadMenuItem);

        appendMenuItem.setText("Append tnsnames.ora");
        appendMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appendMenuItemActionPerformed(evt);
            }
        });
        tnsMenu.add(appendMenuItem);

        menuBar.add(tnsMenu);

        csvMenu.setText("XLS Import");
        csvMenu.setEnabled(false);

        csvUploadMenuItem.setText("Upload XLS");
        csvUploadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csvUploadMenuItemActionPerformed(evt);
            }
        });
        csvMenu.add(csvUploadMenuItem);

        cfgUploadMenuItem.setText("Upload Configuration");
        cfgUploadMenuItem.setEnabled(false);
        cfgUploadMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfgUploadMenuItemActionPerformed(evt);
            }
        });
        csvMenu.add(cfgUploadMenuItem);

        menuBar.add(csvMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(tabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(tabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void xlsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvMenuItemActionPerformed
        addXLSTab();
        checkConnection( DBLoginFrame.UPLOAD_CSV_DATA_SNAPSHOT );
}//GEN-LAST:event_csvMenuItemActionPerformed
    
    
    
    private void csvMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvMenuItemActionPerformed
        addXLSTab();
        checkConnection( DBLoginFrame.UPLOAD_CSV_DATA_SNAPSHOT );
}//GEN-LAST:event_csvMenuItemActionPerformed

    private void connMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connMenuItemActionPerformed
        popUpDBLogin( DBLoginFrame.DO_NOTHING );
}//GEN-LAST:event_connMenuItemActionPerformed

    private void tnsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnsMenuItemActionPerformed
        addTNSTab();
}//GEN-LAST:event_tnsMenuItemActionPerformed

    private void quitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitMenuItemActionPerformed
        System.exit( 0 );
}//GEN-LAST:event_quitMenuItemActionPerformed

    private void uploadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadMenuItemActionPerformed
        popUpFileChooser( FileChooserFrame.UPLOAD_TNS );
}//GEN-LAST:event_uploadMenuItemActionPerformed

    private void appendMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appendMenuItemActionPerformed
        popUpFileChooser( FileChooserFrame.APPEND_TNS );
}//GEN-LAST:event_appendMenuItemActionPerformed

    private void csvUploadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csvUploadMenuItemActionPerformed
        checkConnection( DBLoginFrame.UPLOAD_CSV_DATA_SNAPSHOT );
}//GEN-LAST:event_csvUploadMenuItemActionPerformed

    private void cfgUploadMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfgUploadMenuItemActionPerformed
        popUpFileChooser( FileChooserFrame.UPLOAD_IMAGE );
}//GEN-LAST:event_cfgUploadMenuItemActionPerformed

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMenuItemActionPerformed
        setEnabled( false );
        LicenseFrame licenseFrame = new LicenseFrame( this );
        licenseFrame.setVisible( true );
}//GEN-LAST:event_aboutMenuItemActionPerformed

    /* Add a tab that is used to configure the CSV file to be Uploaded */
   
    public void addXLSTab() {
        xlsPanel = new CSVPanel( this );
        tabbedPane.addTab( "QA XLS File Import", xlsPanel );
        tabbedPane.setSelectedComponent( xlsPanel );
        xlsMenu.setEnabled( true ); // Enable the menu related to CSV Loader
        cfgUploadMenuItem.setEnabled( false );
        csvMenuItem.setEnabled( false );
        welcomePanel.csvLabel.setEnabled( false );
    }
   
    
    
    /* Add a tab that is used to configure the CSV file to be Uploaded */
    public void addCSVTab() {
        csvPanel = new CSVPanel( this );
        tabbedPane.addTab( "QA XLS File Import", xlsPanel );
        tabbedPane.setSelectedComponent( xlsPanel );
        csvMenu.setEnabled( true ); // Enable the menu related to CSV Loader
        cfgUploadMenuItem.setEnabled( false );
        
        /*
            Disable the menu and clickable that open CSV Loader Tab, closing the
            possibility of opening more than one CSV Loader Tabs
         */
        csvMenuItem.setEnabled( false );
        welcomePanel.csvLabel.setEnabled( false );
    }

    /* Add a column to the CSV Data Snapshot, containing the PIDMs derived from other information */
    public void addExistingPIDMCol( int sourceColIndex, int sourceType ) {
        setTitle( "QA XLS Loader hasnat@pv.com - Loading..." );

        try {
            ExistingPIDMQuery pidmQuery = new ExistingPIDMQuery( this, sourceColIndex, sourceType );
            csvPanel.currentImage.add( pidmQuery.getPidms() );
            csvPanel.reloadCSVTable();
        }
        catch( ClassNotFoundException ce ) {
            JOptionPane.showMessageDialog( null, ce.getMessage(), "JDBC Error", JOptionPane.ERROR_MESSAGE );
        }
        catch( SQLException se ) {
            JOptionPane.showMessageDialog( null, se.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE );
        }

        setTitle( "QA XLS Loader hasnat@pv.com" );
        setEnabled( true );
        requestFocus();
    }

    /* Add a new column containing new CSB IDs to the CSV Data Snapshot */
    public void addNewCSBIDCol() {
        setEnabled( false );

        setTitle( "QA XLS Loader hasnat@pv.com - Loading..." );

        try {
            CSBIDGen idGen = new CSBIDGen( this );
            csvPanel.currentImage.add( idGen.getIDs() );
            csvPanel.reloadCSVTable();
        }
        catch( SQLException e ) {
            JOptionPane.showMessageDialog( null, e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE );
        }

        setTitle( "QA XLS Loader hasnat@pv.com" );
        setEnabled( true );
        requestFocus();
    }

    /* Add a new column containing new PIDMs to the CSV Data Snapshot */
    public void addNewPIDMCol() {
        setEnabled( false );

        setTitle( "QA XLS Loader hasnat@pv.com - Loading..." );

        try {
            PIDMGen pidmGen = new PIDMGen( this );
            csvPanel.currentImage.add( pidmGen.getPidms() );
            csvPanel.reloadCSVTable();
        }
        catch( SQLException e ) {
            JOptionPane.showMessageDialog( null, e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE );
        }

        setTitle( "QA XLS Loader hasnat@pv.com" );
        setEnabled( true );
        requestFocus();
    }

    /* Add a new column containing new SJU IDs to the CSV Data Snapshot */
    public void addNewSJUIDCol() {
        setEnabled( false );
        
        setTitle( "QA XLS Loader hasnat@pv.com - Loading..." );

        try {
            SJUIDGen idGen = new SJUIDGen( this );
            csvPanel.currentImage.add( idGen.getIDs() );
            csvPanel.reloadCSVTable();
        }
        catch( SQLException e ) {
            JOptionPane.showMessageDialog( null, e.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE );
        }

        setTitle( "QA XLS Loader hasnat@pv.com" );
        setEnabled( true );
        requestFocus();
    }

    /* Add a tab that is used to maintain the TNS configurations */
    public void addTNSTab() {
        tnsPanel = new TNSPanel( this );
        tabbedPane.addTab( "TNS Maintenance", tnsPanel );
        tabbedPane.setSelectedComponent( tnsPanel );
        tnsMenu.setEnabled( true ); // Enable the menu related to TNS Names Maintenance

        /*
            Disable the menu and clickable that open TNS Maintenance Tab,
            closing the possibility of opening more than one TNS Tabs
         */
        tnsMenuItem.setEnabled( false );
        welcomePanel.tnsLabel.setEnabled( false );
    }

    /* Add a Welcome Tab */
    private void addWelcomeTab() {
        welcomePanel = new WelcomePanel( this );
        tabbedPane.addTab( "Welcome", welcomePanel );
    }

    /* Login to Database before performing a task */
    public void checkConnection( int toDoAfterLogin ) {
        if( user != null ) {
            popUpFileChooser( FileChooserFrame.UPLOAD_XLS );
        }
        else {
            popUpDBLogin( toDoAfterLogin );
        }
    }

    public LinkedList<LinkedList<String>> get2DLinkedList( ArrayList<ArrayList<String>> inArrayList ) {
        LinkedList<LinkedList<String>> outLinkedList = new LinkedList<LinkedList<String>>();

        for( ArrayList<String> rowArrayList: inArrayList ) {
            outLinkedList.add( new LinkedList<String>( rowArrayList ) );
        }

        return outLinkedList;
    }

    public Vector<Vector<String>> get2DVector( ArrayList<ArrayList<String>> inArrayList ) {
        Vector<Vector<String>> outVector = new Vector<Vector<String>>();

        for( ArrayList<String> rowArrayList: inArrayList ) {
            outVector.add( new Vector<String>( rowArrayList ) );
        }

        return outVector;
    }

    public Vector<Vector<String>> get2DVector( LinkedList<LinkedList<String>> inLinkedList ) {
        Vector<Vector<String>> outVector = new Vector<Vector<String>>();

        for( LinkedList<String> rowLinkedList: inLinkedList ) {
            outVector.add( new Vector<String>( rowLinkedList ) );
        }

        return outVector;
    }

    /* Returns a value that is parsed so that it works in SQL DML statements */
    public String getValidatedValue( String value, String dataType ) {
        value = value.trim();

        /*
         *  Do not enclose the value with single quotes (') if it is:
         *  1. sysdate
         *  2. user
         *  3. soundex()
         *  4. wijasa.yukshrd.f_search_name()
         *  5. yukshrd.f_search_name()
         */
        if( value.toLowerCase().equals( "sysdate" ) ||
            value.toLowerCase().equals( "user" ) ||
            value.toLowerCase().matches( "soundex(.*)" ) ||
            value.toLowerCase().matches( "wijasa.yukshrd.f_search_name(.*)" ) ||
            value.toLowerCase().matches( "yukshrd.f_search_name(.*)" ) )
            return value;
        else if( value.equals( "" ) )
            return "null";
        else if( dataType.substring( 0, 4 ).equals( "DATE" ) )
            if( dbType.equals( "MySQL" ) )
                return "str_to_date( '" + value + "', '" + dataType.substring( 6, dataType.lastIndexOf( ")" ) ) + "' )";
            else
                return "to_date( '" + value + "', '" + dataType.substring( 6, dataType.lastIndexOf( ")" ) ) + "' )";
        else {
            value = value.replaceAll( "'", "''" );

            if( dbType.equals( "Oracle" ) )
                value = value.replaceAll( "&", "' || '&' || '" );

            return "'" + value + "'";
        }
    }

    /* Pop Up a Database Column Selector */
    public void popUpDBColSelector() {
        try {
            new ColConfigFrame( this ).setVisible( true );

            setEnabled( false );
        }
        catch( ClassNotFoundException ce ) {
            JOptionPane.showMessageDialog( null, ce.getMessage(), "JDBC Driver Error", JOptionPane.ERROR_MESSAGE );
        }
        catch( SQLException se ) {
            JOptionPane.showMessageDialog( null, se.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE );
        }
    }
    
    /* Pop Up a Database Login Window */
    public void popUpDBLogin( int toDoAfterLogin ) {
        new DBLoginFrame( this, toDoAfterLogin );
        setEnabled( false );
    }

    /* Pop up a File Chooser before performing a task that is related to opening/saving a file */
    public void popUpFileChooser( int task ) {
        if( task == FileChooserFrame.SAVE_DATA_COMPARISON )
            planFrame.setEnabled( false );
        else
            setEnabled( false );
        
        fileChooser = new FileChooserFrame( this, task );
        fileChooser.setVisible( true );
    }

    /* Pop Up a Plan window */
    public void popUpPlanWindow() {
        try {
            planFrame = new PlanFrame( this );

            planFrame.setVisible( true );

            setEnabled( false );
        }
        catch( ClassNotFoundException ce ) {
            JOptionPane.showMessageDialog( null, ce.getMessage(), "JDBC Driver Error", JOptionPane.ERROR_MESSAGE );
            setEnabled( true );
            requestFocus();
        }
        catch( ColumnNotConfiguredException colE ) {
            JOptionPane.showMessageDialog( null, colE.getMessage(), "Column Config Error", JOptionPane.ERROR_MESSAGE );
            setEnabled( true );
            requestFocus();
        }
        catch( SQLException se ) {
            JOptionPane.showMessageDialog( null, se.getMessage(), "SQL Error", JOptionPane.ERROR_MESSAGE );
            setEnabled( true );
            requestFocus();
        }
    }

    /* Save the connection parameters into variables in Main */
    void setConnectionParams( String user, String password, String host, int port, String sid, String dbType ) {
        this.user = user;
        this.password = password;
        this.host = host;
        this.port = port;
        this.sid = sid;
        this.dbType = dbType;

        welcomePanel.userValueLabel.setText( user );
        welcomePanel.hostValueLabel.setText( host );
        welcomePanel.portValueLabel.setText( "" + port );
        welcomePanel.sidValueLabel.setText( sid );
        welcomePanel.dbValueLabel.setText( dbType );
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel( UIManager.getCrossPlatformLookAndFeelClassName() );

            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new Main().setVisible(true);
                }
            });
        }
        catch( Exception e ) {
            JOptionPane.showMessageDialog( null, e.getMessage(), "User Interface Error", JOptionPane.ERROR_MESSAGE );
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem appendMenuItem;
    public javax.swing.JMenuItem cfgUploadMenuItem;
    private javax.swing.JMenuItem connMenuItem;

    public javax.swing.JMenu xlsMenu;
    public javax.swing.JMenuItem xlsMenuItem;
    private javax.swing.JMenuItem xlsUploadMenuItem;
    
    public javax.swing.JMenu csvMenu;
    public javax.swing.JMenuItem csvMenuItem;
    private javax.swing.JMenuItem csvUploadMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu mainMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JSeparator menuSeparator;
    private javax.swing.JMenuItem quitMenuItem;
    public javax.swing.JTabbedPane tabbedPane;
    public javax.swing.JMenu tnsMenu;
    public javax.swing.JMenuItem tnsMenuItem;
    private javax.swing.JMenuItem uploadMenuItem;
    // End of variables declaration//GEN-END:variables

    public Color black; // Clickable Hover Color
    public Color blue;  // Clickable Normal Color
    public Color red;   // Invalid Text Color
    public CSVPanel csvPanel;
    public CSVPanel xlsPanel;
    public FileChooserFrame fileChooser;
    public int port;
    public PlanFrame planFrame;
    public String dbType;
    public String host;
    public String password;
    public String sid;
    public String user;
    public TNSPanel tnsPanel;
    public WelcomePanel welcomePanel;
}
