package jp.elias.xls.form;

public class TNSExceptionFrame extends javax.swing.JFrame {

    /** Creates new form TNSExceptionFrame */
    public TNSExceptionFrame( Main main ) {
        this.main = main;
        initComponents();
        setLocation( main.getX() + 77, main.getY() + 141 );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftScrollPane = new javax.swing.JScrollPane();
        leftTextPane = new javax.swing.JTextPane();
        okButton = new javax.swing.JButton();
        rightScrollPane = new javax.swing.JScrollPane();
        rightTextPane = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TNS Upload Error");

        leftScrollPane.setBorder(null);

        leftTextPane.setBackground(new java.awt.Color(236, 233, 216));
        leftTextPane.setBorder(null);
        leftTextPane.setEditable(false);
        leftTextPane.setText("ERROR: One or more TNS Configuration(s) in the selected file does not follow the following format:\n\n<TNS Name> =\n\t(DESCRIPTION =\n\t\t(ADDRESS =\n           \t\t\t(PROTOCOL = TCP)\n\t\t\t(Host = <Hostname>)\n            \t\t\t(Port = <Port>)\n            \t\t)\n            \t\t(CONNECT_DATA =\n           \t\t\t(SID = <SID>)\n            \t\t)\n           \t)\n\nIn addition, only one line break is allowed between TNS Configurations.");
        leftScrollPane.setViewportView(leftTextPane);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        rightScrollPane.setBorder(null);

        rightTextPane.setBackground(new java.awt.Color(236, 233, 216));
        rightTextPane.setBorder(null);
        rightTextPane.setEditable(false);
        rightTextPane.setText("The following TNSNAMES.ORA syntaxes are not supported:\n- DESCRIPTION_LIST\n- ADDRESS_LIST\n- FAILOVER\n- LOAD_BALANCE\n- RECV_BUF_SIZE\n- SDU\n- SEND_BUF_SIZE\n- SOURCE_ROUTE\n- TYPE_OF_SERVICE\n- FAILOVER_MODE\n- GLOBAL_NAME\n- HS\n- INSTANCE_NAME\n- RDB_DATABASE\n- SERVER\n- SERVICE_NAME\n\nOnly TCP Protocol is supported.");
        rightScrollPane.setViewportView(rightTextPane);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(okButton)
                    .add(leftScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 332, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rightScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 297, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, leftScrollPane)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, rightScrollPane))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(okButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        try {
            if( main.fileChooser.isVisible() ) {
                main.fileChooser.setEnabled( true );
                main.fileChooser.requestFocus();
            } else {
                main.setEnabled( true );
                main.requestFocus();
            }
        } catch( NullPointerException ne ) {
            main.setEnabled( true );
            main.requestFocus();
        }
        dispose();
}//GEN-LAST:event_okButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane leftScrollPane;
    private javax.swing.JTextPane leftTextPane;
    private javax.swing.JButton okButton;
    private javax.swing.JScrollPane rightScrollPane;
    private javax.swing.JTextPane rightTextPane;
    // End of variables declaration//GEN-END:variables

    private Main main;
}
